#Config file: Fallen Kingdom Remastered
##Configuration by KingRider and x9nico:
bungee: false
###DataBase SQL for save stats
mysql:
  enable: false
  host: localhost
  port: 3306
  database: datbase
  user: root
  pass: password
#Finish Config File