#Config file: Fallen Kingdom Remastered
##Configuration by KingRider and x9nico:
bungee: false

##Database for stats
MySQL: false
  user:
  password:
  host:
  database:
  port: 3306
#Finish config file